{
 "title": "Agency Stats",
 "time": { "from": "2020-05-06T12:20:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "RPC calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(ifttt_rpc_request_duration_count[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "RPC messages received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (rate(ifttt_rpc_messages_received[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Number of completed executions by result",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifttt_actionrunner_execution_duration_count[1m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Rule VM initialization duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifttt_ruleengine_rule_vm_initialization_duration_sum[1m])) by (ruleId) / sum(rate(ifttt_ruleengine_rule_vm_initialization_duration_count[1m])) by (ruleId) ",
     "legendFormat": "{{ ruleId }}"
    }
   ]
  },
  {
   "title": "Rule IF evaluation duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifttt_ruleengine_rule_if_evaluation_duration_sum[1m])) by (ruleId) / sum(rate(ifttt_ruleengine_rule_if_evaluation_duration_count[1m])) by (ruleId)",
     "legendFormat": "{{ ruleId }}"
    }
   ]
  },
  {
   "title": "Rule THEN evaluation duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifttt_ruleengine_rule_then_evaluation_duration_sum[1m])) by (ruleId) / sum(rate(ifttt_ruleengine_rule_then_evaluation_duration_count[1m])) by (ruleId)",
     "legendFormat": "{{ ruleId }}"
    }
   ]
  },
  {
   "title": "Distribution of RPC call duration",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(ifttt_rpc_request_duration_bucket[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Distribution of execution duration",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(ifttt_actionrunner_execution_duration_bucket[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Rule evaluation timing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifttt_ruleengine_rule_then_evaluation_duration_sum[1m])) / sum(rate(ifttt_ruleengine_rule_then_evaluation_duration_count[1m]))",
     "legendFormat": "THEN evaluation"
    },
    {
     "expr": "sum(rate(ifttt_ruleengine_rule_if_evaluation_duration_sum[1m])) / sum(rate(ifttt_ruleengine_rule_if_evaluation_duration_count[1m]))",
     "legendFormat": "IF evaluation"
    },
    {
     "expr": "sum(rate(ifttt_ruleengine_rule_vm_initialization_duration_sum[1m])) / sum(rate(ifttt_ruleengine_rule_vm_initialization_duration_count[1m]))",
     "legendFormat": "Initialization"
    }
   ]
  }
 ]
}